### ISSUE TITLE
Use stac-api and raster-api name from config

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#109]
# What
Currently hard-wired names for raster-api and stac-api documentation use the delta prefix and do not reflect deployment stage. Update deployment to use a configured name, i.e. something like `veda-backend-uah-dev-stac` instead of `delta-stac`. Note the API names are included in runtime configuration for each API but are not properly passed through the construct.

# Why
- Naming scheme should use `veda` not `delta`.
- Fixed naming across all deployment stages can make the documentation confusing.

# AC
- [x] Name displayed in `<api-url>/docs` is meaningful for each VEDA stack deployed
- [x] Secrets stored for each deployment are updated

**Comment by j08lue** [comment]
Has this been completed with #89, @anayeaye?

**Comment by anayeaye** [comment]
@j08lue I just confirmed that both acceptance criteria are met (and checked the boxes 😄).
