### ISSUE TITLE
Design github actions workflow for MCP deployment

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#110]
# What
We currently have github actions configured for our UAH test deployment environment using credentials stored in github secrets. Design a solution to obtain MCP credentials and execute appropriate stage deployments on merges into develop and main branches.

## Current github actions workflows
- **Merge request:** lint and test
- **Merge feature/fix into develop branch:** get dev environment configuration from stored UAH AWS secret and execute `cdk diff`
- **Merge develop into main branch:** get staging environment configuration from stored UAH AWS secret and execute `cdk diff`

## Desired workflows
- **Merge request:** lint and test (no change)
- **Merge feature/fix into develop branch:** get dev environment config from stored **MCP** AWS secret and execute **`cdk deploy`**. _It would also be nice to have an automated deployment to the test stack in UAH on a feature/fix merge into the develop branch._
- **Merge develop into main branch:** get production environment configuration from stored **MCP** AWS secret and execute **`cdk deploy`**

# Why
We are entering the operational phase of the VEDA backend APIs and deployments should be automated.

# AC
- [ ] Implement automated stack deployments in github actions workflows 

-or- 

- [ ] Generate design document and issues for work required to automate these deployments.
- [ ] Create necessary tickets to implement automated stack deployments

**Comment by j08lue** [comment]
Happening now in the context of GHGC
