### ISSUE TITLE
Tear down UAH delta-backend in us-east

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#118]
# What
This issue is the follow up to #116 

We have moved production traffic to a new veda-backend in us-west but will persist the legacy delta-backend for a short period to support the transition. After September 2022 there is no reason to keep the us-east delta-backend APIs and ingest pipelines deployed in delta-backend VPCs running so these should all be removed.

# AC
- [x] Communicate sunset date (there are no delta-backends running in us-east that support production applications so this is a courtesy)
- [x] Final snapshot of delta-backend database
- [x] Identify ingest infrastructure deployed in delta-backend VPCs and coordinate the removal of unused infrastructure
- [x] Tear down delta-backend stacks running in us-east

**Comment by smohiudd** [comment]
@anayeaye are we only looking at delta-backend for this teardown? What about legacy step functions for the pipeline?

**Comment by smohiudd** [comment]
I'm starting with `delta-backend-dev` and its associated VPC `vpc-0b0926e1be04a588d`. Looks like parts of that deployment were already torn down. The VPC can't be deleted because it has the following cloud formation stacks associated with it:

```
cog-pipeline-hls
cog-pipeline-hls-dev
cog-pipeline
cog-pipeline-cmr-query
```

Will delete the above stacks after notifying in veda-data-services

**Comment by smohiudd** [comment]
@anayeaye I can see `delta-backend-devv2` and `delta-backend-stagingv2` as well in us-east-1. Do these need to be taken down as well?

**Comment by anayeaye** [comment]
@smohiudd yes, `delta-backend-devv2` and `delta-backend-stagingv2` should go too, thanks for sorting through this!

**Comment by smohiudd** [comment]
The following stacks are using the same VPC as `delta-backend-devv2` and will be deleted:
```
delta-simple-ingest-lambda
hls-ingest-dev-HLSL30-002
```
And the following stack uses the same VPC as `delta-backend-stagingv2`:
```
hls-ingest-stage-hlsl30-002
```
