### ISSUE TITLE
Collection search

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-backend#131]
To fully implement the [analysis page dataset selection](https://github.com/NASA-IMPACT/delta-ui/issues/210) we need a way to know what collections have items for a given aoi and date range.

It would be something like the `/search` endpoint, but instead of returning items, it would just returns a list of collections.

cc @nerik @hanbyul-here @anayeaye

**Comment by danielfdsilva** [comment]
Now that the analysis page was released to production this issue is more visible.

[This url](https://www.earthdata.nasa.gov/dashboard/eis/analysis?start=2010-01-01T00%3A00%3A00.000Z&end=2016-12-31T00%3A00%3A00.000Z&datasetsLayers=lis-tws-anomaly&aoi=~fsia%40~xe~O_ogtcA%3F%3F_sl%7D%60%40~ngtcA%3F) to the analysis definition page spans the whole world with a large date interval, but you can see that only 3 datasets can be selected even though the EIS thematic area has 17. All EPA datasets which date of 2012, should be selectable (within the current parameters), but these three take up all the response items as explained above.

**Comment by aboydnw** [comment]
@danielfdsilva to check my understanding of how we want this to function:

Current state
- The analysis page shows a list of collections for the thematic area that contain data within some part of the selected AOI and span across the ENTIRE date range

Desired state
- The analysis page shows a list of collections for the thematic area that contain data within some part of the selected AOI and at least PART of the date range

Alternative state (I don't think you are saying this, but want to be sure)
- The analysis page shows a list of collections for the thematic area that contain data within some part of the selected AOI REGARDLESS of the date range

**Comment by j08lue** [comment]
@slesaad, can I ask you to give a status update on the collection search?

**Comment by slesaad** [comment]
@j08lue I do not believe that this issue is being worked on currently (you might be thinking of the ingestion API `/collections` endpoint, which is completed already).

This would probably be an addition to the stac fastapi in [NASA-IMPACT/delta-backend](https://github.com/NASA-IMPACT/delta-backend). @anayeaye how easy/difficult do you think this addition will be?

**Comment by j08lue** [comment]
Right, I was mixing up the two, thanks @slesaad. 

I asked the maintainers of https://github.com/stac-utils/stac-fastapi at DevSeed about how to best go about this - whether to try to amend the spec first and then make an implementation. They recommended the other way around: go forward with an implementation in our STAC API and then see later whether this could be relevant for the spec.

**Comment by danielfdsilva** [comment]
@aboydnw The desired state is correct, but the current is:

The analysis page shows a **partial** list of collections for the thematic area that contain data within some part of the selected AOI and at least part of the date range.

This is due to the explanation in the [previous comment](https://github.com/NASA-IMPACT/veda-backend/issues/131#issuecomment-1326475187)

**Comment by anayeaye** [comment]
@danielfdsilva @nerik @hanbyul-here @moradology I am still working through some bugs in the new endpoint proposed for this task and I am revisiting the original ask--an endpoint to determine `what collections have items for a given aoi and date range`. 

I think what we are looking for is essentially a list of distinct collection ids for all items that match an item search? We currently have the groundwork for identifying collection ids by searching the full collection spatial and temporal extent in the collections table (no items are queried).

@moradology I think we should have a look at how we might build on top of the current pgstac item search method and extract distinct collection ids from that to return in the `/collection-id-search` GET and POST endpoints. I suppose we could work on that name, too, to imply that there is an item search under the hood `/item-collection-id-search`.  I assume most/all of the API work would remain the same but the database function will change if we need to support searching for unique collection ids for items matching search criteria.

**Comment by anayeaye** [comment]
Weekend placeholder
Some runnable scratch SQL exploring only datetime and geometry intersects searches. This is not a solution, I just wanted to capture some thoughts.
<details>
  <summary>SQL</summary>

```sql
CREATE OR REPLACE FUNCTION pgstac.zitem_collection_id_search(j jsonb)
 RETURNS text[]
 LANGUAGE plpgsql
AS $function$
DECLARE
    dtrange tstzrange;
    geom geometry;
    sdate timestamptz;
    edate timestamptz;
    collection_ids text[];
BEGIN
    IF j ? 'datetime' THEN
        dtrange := parse_dtrange(j->'datetime');
        sdate := lower(dtrange);
        edate := upper(dtrange);
	END IF;
	IF j ? 'intersects' THEN
		geom := stac_geom(j);
	END IF;
	IF dtrange IS NOT NULL AND geom IS NOT NULL THEN
		SELECT array_agg(distinct collection) INTO collection_ids
		FROM items
		WHERE items.datetime >= sdate
		AND items.datetime <= edate
		AND ST_Intersects(geometry, geom);
		RETURN collection_ids;
	END IF;
	IF dtrange IS NOT NULL AND geom IS NULL THEN
		SELECT array_agg(distinct collection) INTO collection_ids
		FROM items
		WHERE items.datetime >= sdate
		AND items.datetime <= edate;
		RETURN collection_ids;
	END IF;
	IF dtrange IS NULL AND geom IS NOT NULL THEN
		SELECT array_agg(distinct collection) INTO collection_ids
		FROM items
		WHERE ST_Intersects(geometry, geom);
	        RETURN collection_ids;
END IF;
RETURN NULL;
END;
$function$
;
```

**Comment by vlulla** [comment]
I'm curious. Why not use `tstzrange` directly?

```sql
SELECT array_agg(distinct collection) INTO collection_ids
	FROM items
	-- WHERE items.datetime >= sdate
	-- AND items.datetime <= edate
	WHERE items.datetime <@ dtrange -- or dtrange @> items.datetime
	AND ST_Intersects(geometry, geom);
	RETURN collection_ids;
```

I like PostgreSQL's range types because you can do intersection of range/multirange and/or find overlaps (or check if they're before/after/adjacent) of another range/multirange. Just a thought.

**Comment by moradology** [comment]
`dtrange` is fine but, as we have both start/end datetimes and start/end ranges to compare them against, it is likely more efficient to just check that the end time of an item is greater than the start time of the query range and the start time is less than the end of the query range. The difficulties here are about efficiency and dealing with jsonb fields

**Comment by anayeaye** [comment]
This work is related to a FY23 Q2 PI objective: https://github.com/NASA-IMPACT/veda-architecture/issues/162
