### ISSUE TITLE
Cog/validate endpoint is no longer working for protected S3 assets

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#133]
# What
The COG validate, statistics, and info endpoints of the raster-api are no longer working for assets in protected buckets that were previously accessible. The tiling endpoints that use the same access roles are not impacted.

## Notes
For example, the validate endpoint works for an asset in a public bucket:
https://staging-raster.delta-backend.com/cog/validate?url=s3://covid-eo-data/hlss30-ej-reprocessed/2021/15RYP/HLS.S30.T15RYP.2021300T164411.v2.0/HLS.S30.T15RYP.2021300T164411.v2.0.B01.tif

But does not for an asset in a protected bucket:
https://staging-raster.delta-backend.com/cog/validate?url=s3://veda-data-store-staging/EIS/COG/Fire-Hydro/bs_to_save.tif

An older version of the delta-backend is deployed to the MCP account and can be used to validate the co-located protected COGs. It assumes the same veda-data-store-staging-read role as the 'buggy' stack.
https://ny30b7qbm4.execute-api.us-west-2.amazonaws.com/cog/validate?url=s3://veda-data-store-staging/EIS/COG/Fire-Hydro/bs_to_save.tif

# Why
Developers and contributors who do not have direct bucket read access need a way to validate and gather statistics about S3 assets in protected VEDA buckets.

# AC
- [x] `/cog/validate` endpoint does not throw AccessDenied/403 errors for assets in protected S3 buckets in the vedaDataAccessRole and veda-data-store-read-staging role policies.
- [x] _consider:validate_dataset step enabled in veda-stac-ingestor (is temporarily disabled because it uses the broken endpoint--see notes in this [PR](https://github.com/NASA-IMPACT/veda-stac-ingestor/pull/33)). If we plan to implement COG file validation (and not just metadata and accessibility), we should also update veda-stac-ingestor and/or open an issue for the update_

**Comment by smohiudd** [comment]
The raster_api lambda function assumes the following role
```
{
   "Action": "sts:AssumeRole",
   "Resource": "arn:aws:iam::114506680961:role/veda-data-store-read-staging",
   "Effect": "Allow"
}
```
I believe the `veda-data-store-read-staging` role is managed in the MCP account. 

@anayeaye, @ividito do you know if there were any changes to the roles relationship between the raster function and `arn:aws:iam::114506680961:role/veda-data-store-read-staging`. I'm assuming the answer is no because the rest of the raster endpoints are working fine including mosaic

**Comment by anayeaye** [comment]
@smohiudd I checked the `veda-data-store-read-staging` role in MCP and there is no record of a change but that is also what I suspected. I also see no changes to the bucket policy on the veda-data-store-staging bucket. We could try deploying the dev backend with the UAH hosted role (`arn:aws:iam::853558080719:role/vedaDataAccessRole`)--it _should_ have the same permissions, though, so I wouldn't expect this to fix our problem.

**Comment by smohiudd** [comment]
@vincentsarago we're quite stumped with this one, maybe you can help. Do you know of any issues with GDAL or titiler where it could be causing the issue noted above for these [COG endpoints](https://github.com/NASA-IMPACT/veda-backend/blob/a45fbb410b8603f29d29158859048175c12d60bf/raster_api/runtime/src/app.py#L69-L99)? We're only experience these intermittent issues with protected s3 buckets in another account covered by an assume policy.

**Comment by vincentsarago** [comment]
@smohiudd I'm not able to reproduce any issue using the `new test dev backend` 🤷

**Comment by smohiudd** [comment]
Thanks @vincentsarago for looking into this. Turns out it it was simple fix (that took way too much time troubleshooting). The cog/validate endpoint was missing the `AWSSession` env. You can find the pull request here: https://github.com/NASA-IMPACT/veda-backend/pull/144/files
