### ISSUE TITLE
Mangum does not cache database connection pools in AWS Lambda

### ISSUE THREAD

**Issue by vincentsarago** [NASA-IMPACT/veda-backend#142]
https://github.com/NASA-IMPACT/veda-backend/blob/a45fbb410b8603f29d29158859048175c12d60bf/raster_api/runtime/handler.py#L13

ref: https://github.com/stac-utils/stac-fastapi/issues/493
Fix: https://github.com/developmentseed/eoAPI/blob/f559c6a8cc33c94e0b5e57c2a4426dc82bf7df92/stack/handlers/raster_handler.py#L14-L18

**Comment by anayeaye** [comment]
Thanks @vincentsarago and @ividito!
