### ISSUE TITLE
Error requesting statistics using a FeatureCollection

### ISSUE THREAD

**Issue by ividito** [NASA-IMPACT/veda-backend#147]
Originally flagged by @danielfdsilva 

When making a request to to the /statistics endpoint with a Feature Collection, it fails with a 500 error.

url: `https://staging-raster.delta-backend.com/cog/statistics?url=s3://veda-data-store-staging/no2-monthly/OMI_trno2_0.10x0.10_202001_Col3_V4.nc.tif`

body: `{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-11.25,35.73945],[-10.54687,45.73885],[4.21875,43.82883],[3.86719,33.4873],[-11.25,35.73945]]]}},{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-14.41409,50.35231],[5.62497,49.90155],[-5.62503,60.8073],[-14.41409,50.35231]]]}}]}`

Using single features, or a MultiPolygon instead works fine.

The error appears when a newer (>0.8) version of `titiler` is used - this bug might be a good reason to work through the breaking changes of a core dependency upgrade. There may be front-end changes required as part of this upgrade. Most breaking changes are documented [here](https://github.com/developmentseed/titiler/blob/master/CHANGES.md).

**Comment by anayeaye** [comment]
Note on the test geojson example: geojson lint flags the object as invalid. Here is a fixed geojson. The input adjustment does not change the issue in this ticket but I wanted to share in case anyone else goes down that road.

`{"type": "FeatureCollection", "features": [{"type": "Feature", "properties": {}, "geometry": {"type": "Polygon", "coordinates": [[[-11.25, 35.73945], [3.86719, 33.4873], [4.21875, 43.82883], [-10.54687, 45.73885], [-11.25, 35.73945]]]}}, {"type": "Feature", "properties": {}, "geometry": {"type": "Polygon", "coordinates": [[[-14.41409, 50.35231], [5.62497, 49.90155], [-5.62503, 60.8073], [-14.41409, 50.35231]]]}}]}`

**Comment by vincentsarago** [comment]
The issue is somewhere in pydantic/geojson-pydantic but I'm not able to pinpoint exactly where. I tried to only update those library (not updating rio-tiler) but it didn't solve the issue :-(
