### ISSUE TITLE
Include vector features child link in collections

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-backend#152]
## PI Objective

[Improve vector data visualization & vector metadata discovery#167](https://github.com/NASA-IMPACT/veda-architecture/issues/167)

## Description

Vector features API will be included as a [child link](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#relation-types) in STAC collections. We will need to dynamically add the link to the collection if a STAC collection includes vector features.

## Acceptance criteria 

- [ ] Vector data collections are listed in VEDA STAC with a child link pointing to the Vector Features API

**Comment by j08lue** [comment]
Related to https://github.com/NASA-IMPACT/veda-architecture/issues/123, just for vector data.

**Comment by smohiudd** [comment]
Had a discussion with @moradology about this. Since only certain collections will be vector datasets, the link injection scripts as outlined in this veda-backend [PR](https://github.com/NASA-IMPACT/veda-backend/pull/146/files) may not work since we need a way to distinguish which collections are vector. Some potential ways to do this include:

- including custom properties in the STAC collection like `vector:True`. 
- specifying a vector asset type as referenced in the [spec ](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#asset-object). It's unclear if there's an appropriate "vector" asset type that we could use here
- query or search other collection attributes that include "vector", "features" etc. Not very deterministic and may lead to errors. 

Another, simpler option may be to have the user include the stac collection vector child link directly when they are defining their collection in JSON.. I.e.
```
{
   "id": "eis_fire_fireline",
   "type": "Collection",
   "links":[
      {
         "rel": "child",
         "type": "application/json",
         "href": "https://pzh7fedpc0.execute-api.us-west-2.amazonaws.com/collections/public.eis_fire_fireline"
      }
   ],
   "title":"EIS Fireline dataset",
   "extent":{
      "spatial": {
         "bbox": [
               [
                  -123.99217987060547,
                  31.054306030273438,
                  -101.49222564697266,
                  49.461177825927734
               ]
      ],
         "crs": "http://www.opengis.net/def/crs/EPSG/0/4326"
      },
      "temporal": {
         "interval": [
                  [
                     "2019-05-01T00:00:00+00:00",
                     "2020-10-31T12:00:00+00:00"
                  ]
      ],
         "trs": "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"
      }
   },
   "license":"public-domain",
   "description": "EIS Fireline dataset",
   "stac_version": "1.0.0",
   "dashboard:is_periodic": true,
   "dashboard:time_density": "day"
}
```
Curious if anyone has any thoughts on the above approach?

**Comment by anayeaye** [comment]
@smohiudd I think adding the child link manually is the right approach to get things started--maybe after we add and use a few vector collections we will start to see the best pattern to try configuring dynamic collection-level links to a veda-ecosystem vector server.

- I am realizing that our item-based automated collection summaries could end up wiping out the temporal and spatial extents for these vector collections. If/when we upgrade pgstac there is an option to automatically update these extents on a cron so we'll need to keep an eye on that. No action here, just bringing it up.

- I think there might be a way for us to make use of the item_assets property of the collection to advertise the child items. I was going to mock something up but can't find a link to a vector at the moment so this is just an attempt to play with the idea without the data in hand. I'm not necessarily recommending anything about this stub
```
"item_assets": {
    "detection": {
        "type": "application/geo+json",
        "roles": [
              "data",
              "layer", 
              "geometry" 
        ],
        "title": "Detection",
        "description": "Externally hosted geometry representing a single detection"
    }
}
```

**Comment by smohiudd** [comment]
Thanks @anayeaye for your feedback. Good to know about collection temporal/spatial updates. The vector collections won't have any items stored in the stac db so wondering if the vector collections will be affected. 

Here is a sample collection from the features API for your info: https://firenrt.delta-backend.com/collections/public.eis_fire_fireline?f=json

For sure we can look into including the item assets property as well. I wasn't able to find any information on `item_assets` in the [STAC spec ](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#assets) - do you have any information on this?

**Comment by smohiudd** [comment]
I was able to find the `item_assets` stac extension spec here: https://github.com/stac-extensions/item-assets

**Comment by smohiudd** [comment]
Since we are not making any changes to `veda-backend` at this time for vector link injection, I think we can close this ticket.
