### ISSUE TITLE
Investigate upgrading pgSTAC version

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#154]
# What
The pgSTAC version used by the veda-backend is behind the main release. Investigate the lift to upgrade the version so that it is easier to integrate fixes.

# PI Objective
https://github.com/NASA-IMPACT/veda-architecture/issues/164 

# AC Answer These Questions
- [ ] should we upgrade pgSTAC?
- [ ] what projects will need to be updated if the version is changed (i.e. the veda-stac-ingestor uses a versioned pypgstac)?
- [ ] what other steps would be needed to upgrade and migrate the database to a newer version of pgSTAC?

**Comment by anayeaye** [comment]
Some pros for upgrading to > 0.7.0
- from David: the temporal extent in the code that is in 0.7 takes the full extent from the min(datetime) max(end_datetime)
- There is functionality for updating collection extents automatically (no manual trigger)

**Comment by smohiudd** [comment]
I had a chat with @bitner about this and it seems the pgstac upgrade migration will be straight forward without any breaking changes. It should be able to run in the cdk bootstrap in `veda-backend`:

`Migrate(pgdb).run_migration(params["pgstac_version"])` 

Also the automatic collection extent update can be implemented using the pgstac_settings table. But note that the extent update can't handle multi polygon extents and instead will have a single bounding box extent - I don't think this should be a problem in veda. 

Another thing to note about v0.7.0 is that it includes a "use_queue" configuration parameter that allows deferred processing for building indexes, adding constraints and updating partitions. This would effectively defer these overhead processes for later using some chron job and would overcome having to complete them at time of ingest. This is an opt in feature so not necessary to implement right now, but something to think about for our stack.

**Comment by smohiudd** [comment]
The pgstac upgrade planning ticket is documented here: https://github.com/NASA-IMPACT/veda-architecture/issues/242#issuecomment-1524111402. This one can be closed.
