### ISSUE TITLE
Upgrade to python 3.9

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#162]
# What
Upgrade to python 3.9, work is started in PR #160 or a new branch can be created.

# PI Objective
https://github.com/NASA-IMPACT/veda-architecture/issues/164

# AC
- [x] existing tests and deployment scripts run as expected

**Comment by anayeaye** [comment]
PR #160

**Comment by anayeaye** [comment]
These changes are merged into develop and successfully deployed to the dev stack.

**Comment by j08lue** [comment]
Tested, too? Because then we could tick off and close this ticket. 😄

**Comment by anayeaye** [comment]
#167 merged and deployed and dev API now working as expected
