### ISSUE TITLE
Run tests in containers

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#163]
# What
Upgrade to python 3.9, work is started in PR #160 or a new branch can be created.

# PI Objective
https://github.com/NASA-IMPACT/veda-architecture/issues/164

# AC
- [x] scripts/bin/* shell scripts created and mounted in database, stac, and raster containers on docker compose
- [x] .github/workflows/data mounted in database container for loading
- [x] scripts/* contain `docker exec <container name> <command> to load database and to run tests on stac and raster containers
~~- [ ] .github workflows updated to use above scripts/containers instead of managing python environments on github runner~~

**Comment by ividito** [comment]
I had some failing tests in #148, so I've picked this up and will include the scripts there.

**Comment by j08lue** [comment]
Will get closed with #148.
