### ISSUE TITLE
Correct proj extension values <and schema> in pgstac

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#166]
# What
The batch loading step of our ingest system caused proj values to be stored as float instead of int. This is acceptable for the older version of the proj extension (0.0.1) but requires a work around for users of the VEDA stac-api. 
1. `proj` values should be stored as int
2. `proj` extension should be upgraded to 0.1.0 _if_ it is decided to upgrade the extension for newly created records.

For forward ingests, the values will be fixed in an [upgrade to the ingest API](https://github.com/NASA-IMPACT/veda-architecture/issues/215) and the stac extension for new records is addressed in [this pipelines tasks issue](https://github.com/NASA-IMPACT/veda-pipeline-tasks/issues/9). When the ingest systems are updated, this issue is to apply a backwards correction to all of the currently ingested records. If this can be executed safely in the database, engage @bitner for a review, if the backward correction cannot be safely executed, open issues to re-ingest impacted records.

## Bug reported in pipelines
https://github.com/NASA-IMPACT/veda-data-pipelines/issues/313

# AC
- [x] `proj` values should be stored as int
- [ ] `proj` extension should be upgraded to 0.1.0 _if_ it is decided to upgrade the extension for newly created records.

**Comment by emileten** [comment]
> this issue is to apply a backwards correction to all of the currently ingested records

Hi @anayeaye ! We want to do the same thing in MAAP (backwards correction). I was in particular wondering if there is a quicker solution than re-ingesting impacted records. I remember hearing last week or so from @bitner that it is possible to do that with a direct connection to the database, wondering what this would look like ? Thank you !

https://github.com/NASA-IMPACT/active-maap-sprint/issues/489

**Comment by anayeaye** [comment]
@emileten thanks for linking the issues so we can compare notes throughout the fix (when we get started)! Fixing the records in place is definitely preferable to re-ingesting.

**Comment by moradology** [comment]
Hey! So this SQL ought to do the trick for getting EPSGs into the right format (tested in dev so far):
`UPDATE items SET content = jsonb_set(content, '{properties, proj:epsg}', to_jsonb(CAST((content->'properties'->'proj:epsg') AS INTEGER)), true) WHERE content->'properties'->>'proj:epsg' IS NOT NULL;`

**Comment by moradology** [comment]
I didn't see that the shape field also has the wrong types 🤦. To avoid losing this work, I'll add some scripts for one off repair of these fields (instead of saving it as a UDF w/in the database, as this seems pretty unlikely to be generally useful in the future)

**Comment by moradology** [comment]
This PR includes a fix for shape (as well as some reusable logic if that's helpful): https://github.com/NASA-IMPACT/veda-backend/pull/175
