### ISSUE TITLE
Upgrade ecosystem to pgSTAC > 0.7

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#176]
# What
We are maintaining this database for the long term and need to begin to add routine pgSTAC schema upgrades to our maintenance schedule. For each stage of the VEDA ecosystem the maintenance should include:

0. Record the approximate time it takes to execute each step in this process (it will help inform future pgstac and RDS upgrade plans)
1. Migrate pgSTAC schema to the latest recommended version
3. Update pypgstac version used veda-stac-ingestor to match the database version
4. Nice-to-have: Test stac-api, raster-api, and open a veda-config PR for the dev APIs to confirm that the dashboard functions as expected

# PI Objective  
[Objective 223](https://github.com/NASA-IMPACT/veda-architecture/issues/223)
[Epic 242](https://github.com/NASA-IMPACT/veda-architecture/issues/242)

# Basic Testing Notes
While we are working out our standard operation procedures for updating the ecosystem, here are some notes for testing that the change is non breaking. Should be very simple to touch each system, we aren't going for coverage yet.
- STAC API: /docs are reachable and browsing appears to work as expected
- Raster API: /docs are reachable and tiling appears to work as expected (for example try the cog viewer and a notebook in veda-documentation)
- Ingest systems working: whether running from a separate instance of veda-stac-ingestor or from the planned integrated ingest-api, we should be able to publish a collection and an item (re publish something we already have).
- Nice to have: open a do not merge veda-config PR to confirm that the develop APIs support the dashboard as expected

# AC
- [x] measurements for individual steps of the migration and ecosystem upgrade are recorded to plan future maintenance windows
- [x] dev update duration used to plan and advertise the staging upgrade (a formality for VEDA developers and EO Dashboard developers) 
- [x] dev stage of veda-backend and veda-stac-ingestor upgraded to the same version and baseline smoke tests performed after deployment
- [ ] staging stage of veda-backend and veda-stac-ingestor upgraded to the same version and baseline smoke tests performed after deployment

**Comment by smohiudd** [comment]
I opened a PR to upgrade `dev` veda-backend pgstac but the deploy workflow failed because of an import error for `urllib3` which is used via`requests`: https://github.com/NASA-IMPACT/veda-backend/pull/180

Going to try again with another pull request with `urllib3<2`

**Comment by smohiudd** [comment]
There's a [bug](https://github.com/stac-utils/pgstac/issues/180) with the migration to 0.7.6 so had to go with 0.7.4 instead. The upgrade to the `dev` deployment was successful and the migration took about 30 mins according to the cloudwatch logs.
