### ISSUE TITLE
Could collection_id_search be achieved with a parameter in an item search?

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#179]
# What
We are preparing to release a new endpoint `collection_id_search/` which returns a unique list of collection ids for items matching a search criteria. This is important to users who want to discover what collections contain items meeting spatial and temporal criteria (dashboard for example).

Collection_id_search is essentially implemented an item search behind the scenes. Could we instead add an optional parameter to the stac-api item search that would return unique matched collections? I.e. something like `stac_base_url/search?distinct_collection_ids=true`? Could our stac-api still be spec compliant with this additional parameter?

# AC 
- [ ] discussion in issue

**Comment by jsignell** [comment]
I am asking around to see if this is the kind of thing that AggregationExtension wants to handle

**Comment by jsignell** [comment]
Ok so apparently this is very much something that the aggregation extension wants to do:

> /aggregate takes the same parameters as search, and you could define an aggregation "collections" that has the collection ids as buckets and the count as how many items match for each one

**Comment by jsignell** [comment]
I still don't really understand how aggregations are meant to work, but I'm messing around with https://earth-search.aws.element84.com/v1/aggregate

**Comment by anayeaye** [comment]
@jsignell that sounds great, I think the guts of the collection_id_search in veda-backend might be extensible to building an `/aggregate` endpoint? 

Last I looked I remember seeing an aggregation metadata spec for collection summaries but the api-spec [/aggregate](https://github.com/stac-api-extensions/aggregation) looks like it addresses the dashboard need to find what collections contain items meeting search criteria. Not including a collections filter in the pgstac items search makes it pretty slow but I'm super interested to learn how other implementations are working.

**Comment by jsignell** [comment]
Yeah you are way ahead of me! I was just trying https://earth-search.aws.element84.com/v1/collections/naip/aggregate?aggregations=total_count

**Comment by jsignell** [comment]
Oh!! Look at this: https://earth-search.aws.element84.com/v1/aggregate?aggregations=collection_frequency

**Comment by jsignell** [comment]
And you can add basically any search fields: https://earth-search.aws.element84.com/v1/aggregate?aggregations=collection_frequency&datetime=2018-02-12T00:00:00Z/2018-03-18T12:31:12Z

**Comment by jsignell** [comment]
Right so if I understand what you are saying: we still need a fast way to populate a response from an `/aggregate` endpoint. I imagine the spot for that would be stac-server right?

**Comment by anayeaye** [comment]
I'm less clear on the how. VEDA's implementation is PgSTAC+stac-fastapi. PgSTAC contains the logic for searching items stored as jsonb in a postgres. I think the aggregation would need to be generated in the pgstac database?

**Comment by anayeaye** [comment]
Closing this discussion issue but we will link to this issue in a future ADR for managing aggregated collection information for dashboard and downstream users.
