### ISSUE TITLE
Perform stress testing on titiler API

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [NASA-IMPACT/veda-backend#201]
This issue aims to plan and execute a comprehensive stress testing strategy on the titiler API, identify any performance bottlenecks, and optimize its scalability.

**Comment by j08lue** [comment]
Done and recently demo'ed for GHG Center. Perhaps documentation should be moved to / referenced in https://github.com/NASA-IMPACT/veda-architecture/wiki, @amarouane-ABDELHAK ?
