### ISSUE TITLE
Improve RDS configurability

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#206]
# What
1. Make RDS construct instance type configurable with a sensible default
2. Make Postgres engine version configurable
3. Add configuration parameters to support deploying new encrypted RDS instances

# Why
Hard coded default instance type is small and will need to be increased as usage increases (especially public facing implementations like GHGC)
Postgresql engine version should be updated periodically for latest improvements and security upgrades from AWS and veda-backend CDK should support instantiating new versions of the backend with the latest postgresql engine.

# PI Objective
https://github.com/NASA-IMPACT/veda-architecture/issues/285

# AC
- [x] Tested impact of changes on existing database (what is downtime? does the change cause the database to be destroyed?)
- [x] Dev and staging database in lower environments can be safely deployed without user impact.
- [x] RDS instance size/type configurable 
- [x] RDS postgres engine version is configurable
- [x] RDS encryption configurable
~[ ] All RDS instances in MCP are encrypted~ (RDS for veda-backend is fully configurable)

**Comment by slesaad** [comment]
Added the configuration option in GHGC: https://github.com/US-GHG-Center/ghgc-backend/pull/16/files

**Comment by anayeaye** [comment]
@amarouane-ABDELHAK I added you to this issue because you've already done some of the work in GHG. Hope that's OK! Will probably ping you on the VEDA PRs when we integrate the changes...

**Comment by amarouane-ABDELHAK** [comment]
I have submitted a PR to configure to make the size and the type of RDS configurable: [RDS PR](https://github.com/US-GHG-Center/ghgc-backend/pull/29/files#diff-0b6fcf3aae2720251df54b51981a6a5c982a375bd6e2fc3ea6a8d9617aac2acc)

**Comment by anayeaye** [comment]
Here's GHGC's update for configuring RDS encryption https://github.com/US-GHG-Center/ghgc-backend/pull/34

**Comment by anayeaye** [comment]
https://github.com/NASA-IMPACT/veda-backend/pull/218#pullrequestreview-1594354621

**Comment by anayeaye** [comment]
Update: most unencrypted RDS have been removed we still need to replace a backend-prod and a fapi-prod with encrypted instances.

**Comment by anayeaye** [comment]
This issue was intended to add configurability to RDS veda-backend and we can now deploy new instances as encrypted, and for existing/new we can configure postgres engine version, instance type and size so the task is complete. The operational need will be resolved in the mono-repo production deployments in progress.
