### ISSUE TITLE
Chore: remove alt-domain support

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#221]
## What 
Remove configuration and support for hosting duplicate stac and raster apis at alternative domains.

## Why
The alt domain config and construct supported a one-off operational need for hosting multiple copies of the stac and raster apis at different custom domain urls. Removing this fix that is no longer needed or in use is a clean up chore only to make the project more readable.

## AC
- [ ] alt domain support removed from config and app construct

**Comment by anayeaye** [comment]
https://github.com/NASA-IMPACT/veda-backend/pull/422 is going to close this issue

**Comment by botanical** [comment]
https://github.com/NASA-IMPACT/veda-backend/commit/d6aedd75b9751b35c980e85ffc305933e0a87681
