### ISSUE TITLE
Fix CORS issue from staging to production

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [NASA-IMPACT/veda-backend#233]
Staging environment is experiencing CORS issues when trying to access production resources (stac api).

First attempt to fix this is to allow cloudfront in prod to allow-cross-origin header

**Comment by amarouane-ABDELHAK** [comment]
![Image](https://github.com/NASA-IMPACT/veda-backend/assets/33136280/b6bf957c-d6e3-4f22-83a2-f4da064e5e4c)

**Comment by amarouane-ABDELHAK** [comment]
Adding `CORS-With-Preflight` policy to the cloudfront (stac behavior) solved the CORS problem we experienced in `staging`
![image](https://github.com/NASA-IMPACT/veda-backend/assets/33136280/93fa04c3-d14f-4213-b23d-f1546cf8473a)
Same policy was added to raster behviore just in case.

**Comment by amarouane-ABDELHAK** [comment]
Done

**Comment by j08lue** [comment]
Do we actually have IAC for this or does this need to be done manually?

**Comment by amarouane-ABDELHAK** [comment]
As far as I know, the CloudFront distributions are provisioned manually, and still require manual configuration
