### ISSUE TITLE
Upgrade titiler-pgstac

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-backend#234]
## Large backlog

TiTiler-PgSTAC is now at 0.8.0 and we are still at 

https://github.com/NASA-IMPACT/veda-backend/blob/e4b02a54bc043e87f28a68334b10cc5d2e9211ed/raster_api/runtime/setup.py#L9

This is blocking a number of features that were implemented upstream in TiTiler, which we need in VEDA, most notably

- #226 

## Complications

There have been some breaking API changes in TiTiler between the latest version and what we have, so any update will need to be coordinated with dependants - the VEDA Dashboard and the EO Dashboard.

## Acceptance criteria

- [x] Mapped out breaking changes
- [x] Deployed to a "staging" stack for the Dashboard(s) to build against
- [x] Upgraded TiTiler-PgSTAC

**Comment by vincentsarago** [comment]
Most of the breaking changes (Some of them only concern the main application of titiler-pgstac so it might not be relevant):


- Use `/collections/{collection_id}/items/{item_id}` prefix for Item endpoint.
```
# Before
{endpoint}/stac/info?collection=collection1&item=item1

# Now
{endpoint}/collections/collection1/items/item1/info
```

- change tile url path parameter order from `/tiles/{searchid}/{TileMatrixSetId}/{z}/{x}/{y`} to `/{searchid}/tiles/{TileMatrixSetId}/{z}/{x}/{y}`

```
# Before
{endpoint}/mosaic/tiles/20200307aC0853900w361030/0/0/0

# Now
{endpoint}/mosaic/20200307aC0853900w361030/tiles/0/0/0
```

- replace `/{searchid}/{z}/{x}/{y}/assets` endpoints by `/{searchid}/tiles/{z}/{x}/{y}/assets`

- use `/api` and `/api.html` for documentation (instead of /openapi.json and /docs)

- add landing page `/`

- replace - by _ in query parameters

    - coord-crs -> coord_crs
    - dst-crs -> dst_crs

- remove `max_size` default for mosaic's `/statistics [POST]` endpoint breaking change

- add `/bbox` and `/feature [POST]` optional endpoints

**Comment by anayeaye** [comment]
I created a test stack with the new titiler and a copy of the staging database that I needed for testing the veda-docs 
https://test-stac.delta-backend.com/
https://test-raster.delta-backend.com/

**Comment by hanbyul-here** [comment]
Adding more changes that were commented on the original PR (Thanks @anayeaye for thoroughly going through the changes!)

- Use algorithum instead of post_process: https://github.com/NASA-IMPACT/veda-backend/pull/239#discussion_r1360872815

**Comment by anayeaye** [comment]
[Veda-config PR](https://github.com/NASA-IMPACT/veda-config/pull/334?expand=1&template=default.md) with algorithm change.

**Comment by j08lue** [comment]
We need another version upgrade for `rio-tiler` to include this bug fix, please:

- https://github.com/cogeotiff/rio-tiler/pull/653

**Comment by vincentsarago** [comment]
Note: 

any re-deploy will include the new rio-tiler fix (because rio-tiler is not pin to specific version 🙏) 

#246 will be nice to have if we want to use the custom algorithm instead of eqa projection!

**Comment by anayeaye** [comment]
@j08lue @slesaad ghgc-dev(smce) and veda-dev are both running rio-tiler 6.2.6 (w/validate shape in coverage)

**Comment by j08lue** [comment]
Awesome, @anayeaye and @vincentsarago, this now works:

```python
import requests

RASTER_API_URL = "https://dev.ghg.center/api/raster"

ITEM_ASSET_URL = "s3://veda-data-store-staging/no2-monthly/OMI_trno2_0.10x0.10_202109_Col3_V4.nc.tif"

AOI = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          [
            [
              -115,
              82
            ],
            [
              -115,
              -82
            ],
            [
              -43,
              -82
            ],
            [
              -43,
              82
            ],
            [
              -115,
              82
            ]
          ]
        ],
        "type": "Polygon"
      }
    }
  ]
}

result = requests.post(
    f"{RASTER_API_URL}/cog/statistics",
    params={
        "url": ITEM_ASSET_URL,
        "dst_crs": "+proj=cea"
    },
    json=AOI["features"][0],
)
result.raise_for_status()
result.json()
```

and give different results whether I set `dst_crs` or not.

**Comment by j08lue** [comment]
I can also confirm that the results of the case with `+proj=cea` agree with the weighted average calculated with the scientist-provided method:

![image](https://github.com/NASA-IMPACT/veda-backend/assets/3404817/39d249a6-9c18-4d48-864c-264958006502)
