### ISSUE TITLE
Include rendered preview links using render stac extension

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-backend#251]
Using the new [render stac extension](https://github.com/stac-extensions/render), `rendered_preview` and `preview` links can be added to items using titiler parameters. 

This can build off previous work by @moradology regarding various link injection: https://github.com/NASA-IMPACT/veda-backend/pull/146

Since this will require looping through item collections and injecting links, need to assess performance impacts if any. 

## Acceptance Criteria 

- [x] Test stack deployed with rendered_preview and preview links for various collections
- [ ] Measure request timings with/without render link injection, assess performance 
- [x] Deployed to `dev` stack

**Comment by smohiudd** [comment]
Test stack deployed: https://render-test.delta-backend.com/api/stac/collections

Render links are applied to the following collections: 

- geoglam
- houston-aod
- bangladesh-landcover-2001-2020
- barc-thomasfire

**Comment by smohiudd** [comment]
PR: https://github.com/NASA-IMPACT/veda-backend/pull/247

**Comment by smohiudd** [comment]
Render parameters included in `veda-data`: https://github.com/NASA-IMPACT/veda-data/pull/88

**Comment by j08lue** [comment]
FYI - we briefly showed how the rendered previews show up in [STAC Browser for the test deployment](https://radiantearth.github.io/stac-browser/#/external/render-test.delta-backend.com/api/stac/collections/bangladesh-landcover-2001-2020) during the VEDA team status updates and it was very well received. 👏
