### ISSUE TITLE
Create a communication setup between STAC endpoint and Amazon RDS using RDS Proxy

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [NASA-IMPACT/veda-backend#272]
The goal of this task is to optimize database connectivity and improve performance by efficiently managing and reusing database connections through the use of AWS RDS Proxy. RDS Proxy contributes to the scalability of the application, allowing the system to handle increased user demand more efficiently as the workload grows

**Comment by anayeaye** [comment]
completed in #287
