### ISSUE TITLE
Ingest API token endpoint bug

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#280]
## What
Behind proxy, the ingest api `token/` endpoint throws a cloudfront error

Using the api gateway directly, the token endpoint times out

## Where
- veda-uah
- cloudfront url: https://dev.delta-backend.com/api/ingest/docs
- apigw url: https://77451h4b35.execute-api.us-west-2.amazonaws.com/docs

## How you can investigate
1. Confirm which cognito pool the dev veda-backend instance is using for auth (during debugging this has been toggled between `veda-auth-stack-dev` and `veda-auth-stack-uah`). You can confirm by finding the lambda in the console and checking the environment config or reading the `veda-backend-uah-dev-env` secret
2. Add yourself to the user pool if you are not already in it. Here are [tips for setting your password the first time](https://github.com/NASA-IMPACT/veda-architecture/wiki/Operations-Troubleshooting-Cheatsheet#everyone-else-handle-password-reset-challenge-aws-cognito-idp-initiate-auth).
3. Try out the /token endpoint with username password

## AC
- [x] Operator can obtain a valid token with user password flow and confirm it with the `auth/me` endpoint

**Comment by anayeaye** [comment]
I just got and validated a token at https://dev.delta-backend.com/api/ingest/docs#

**Comment by botanical** [comment]
Work was done (https://github.com/NASA-IMPACT/veda-backend/pull/281) and tested so I will be closing this issue.
