### ISSUE TITLE
Testing RDS Proxy and Connection Pooling

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-backend#287]
## What 

The existing backend RDS implementation cannot support a large number of concurrent connections to the database and may exhaust available compute and memory resources. 

A [RDS Proxy](https://aws.amazon.com/rds/proxy/) configuration is available in Veda Backend, however this service has not been tested or configured.  

## PI Objective

[Objective 2: Production Services: CI Updates and Monitoring](https://github.com/NASA-IMPACT/veda-architecture/issues/358)

## Acceptance Criteria 

- [x] confirm veda-backend can be deployed without an RDS Proxy construct (ensure that this change is not breaking for operational stacks)
- [x] dev stage of veda-backend deployed with RDS Proxy and supports connection pooling
- [x]  load test applied and documented
- [x] either deploy staging stage of veda-backend with RDS Proxy or open issue to manage the roll out

**Comment by anayeaye** [comment]
Note: the frontend is currently experiencing problems with high volume/batched statistics requests for analysis features in the dashboard and we can probably work directly with the dashboard team on the load testing. 
https://github.com/NASA-IMPACT/veda-ui/pull/815
https://github.com/NASA-IMPACT/veda-ui/pull/817

**Comment by amarouane-ABDELHAK** [comment]
A [PR](https://github.com/NASA-IMPACT/veda-backend/pull/299) was created for testing RDS proxy

**Comment by anayeaye** [comment]
## RDS Proxy to dev plan
1. confirm everything is ok in dev now
  - [UPDATE THIS PR](https://github.com/NASA-IMPACT/veda-config/pull/358) config with `openveda.cloud` cloudfront urls then, https://deploy-preview-358--visex.netlify.app/
  - https://dev.openveda.cloud/api/stac/collections
  - https://radiantearth.github.io/stac-browser/#/external/dev.openveda.cloud/api/stac/?.language=en
  - http://dev.openveda.cloud/api/raster/cog/viewer?url=s3://veda-data-store-staging/no2-monthly/OMI_trno2_0.10x0.10_202210_Col3_V4.nc.tif
2. merge w/o updating env vars (this will show that we can deploy successfully w/o a proxy
3. run through same checks above
4. update env vars to use proxy and re-trigger action
5. re test
