### ISSUE TITLE
Explore stac-fastapi bulk transactions

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-backend#296]
## What

Stac Fast API has a [bulk transactions extension](https://stac-utils.github.io/stac-fastapi/api/stac_fastapi/extensions/third_party/bulk_transactions/) which allows the bulk insertion of items. This could compliment our existing ingestion process but must be tested for stability and features. Bulk ingestion may have been used in the CSDA project but needs to be confirmed. 

## Acceptance Criteria

- [ ] Bulk transaction extension is added to stac API and tested in a [SIT environment](https://github.com/NASA-IMPACT/veda-architecture/wiki/DS:-Infrastructure#quickstart-veda-backend-sit-stack).

**Comment by anayeaye** [comment]
https://github.com/NASA-IMPACT/veda-backend/pull/378
