### ISSUE TITLE
Dependabot Alerts

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#297]
## What
https://github.com/NASA-IMPACT/veda-backend/security/dependabot/1

https://github.com/NASA-IMPACT/veda-backend/security/dependabot/2

## Note
We've pinned starlette in the raster-api on an earlier version to avoid this `[ERROR] AssertionError: either 'directory' or 'env' arguments must be passed`

AC

- [x] deployed to dev
- [x] veda-config check

**Comment by smohiudd** [comment]
@vincentsarago what's the recommended version of starlette we should be using for titiler? We've currently pinned `starlette<0.28`

**Comment by vincentsarago** [comment]
@smohiudd tbh I always deferred the starlette pining to fastAPI so it depends on which titiler version you use
