### ISSUE TITLE
Feedback on stac-admin UI

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-backend#304]
## What

A test [STAC Admin UI](https://github.com/developmentseed/stac-admin) was deployed to https://d1fzab3z0mlfhy.cloudfront.net/

Before further developing this feature for VEDA, the team needs to collect feedback from stakeholders.

## Acceptance Criteria

- [x] List of relevant stakeholders collected 
- [x] Feedback received from stakeholders that can inform further development of STAC Admin for VEDA

**Comment by smohiudd** [comment]
Generative interview questions for STAC Admin are outlined in this document: https://docs.google.com/document/d/1clRi0m13zMbdtLgrsK6Ou_3swE5cS0j4THOK3IwgGHk/edit

@aboydnw, @oliverroick can you please have a look and let me know if you have any comments.

**Comment by aboydnw** [comment]
Just dropped some comments, I like where this is going and that we are doing this! Do we have an idea yet on the scheduling front? Are we already in contact with users and coordinating days/times? In the past working with somebody like Jerika has also been helpful.

**Comment by smohiudd** [comment]
Thanks @aboydnw! I'm working on scheduling the interviews and reached out to Jerika on some potential users.

**Comment by smohiudd** [comment]
Interview with @siddharth0248 and @SwordSaintLancelot held on May 29. Notes: https://docs.google.com/document/d/1clRi0m13zMbdtLgrsK6Ou_3swE5cS0j4THOK3IwgGHk/edit

**Comment by slesaad** [comment]
Some feedback from playing around with STAC Admin, having a lot of experience publishing datasets, and seeing other people publish datasets.

- Ability to create a new collection with required fields + additional fields
- Edit all the fields that are present in a collection/item (not just a subset)
- Ability to apply a change to all collections / all items in a collection or a select list of collections
  - example for things like `stac-extensions` or `license` or `renders.colormap_name`
- License field should be a dropdown of all the valid values
- Validation of fields (ex - url provided is valid and returns a 2XX response; if stac-extensions is provided, check the schema validity)

Awesome to have
- Templatization
  - an example would be: to add thumbnail url to all collections, provide a field where an user can do something like this:
    `https://thumbnails.openveda.cloud/${collection_id}.png` - apply to all collections

**Comment by smohiudd** [comment]
Thanks @slesaad for this feedback!
