### ISSUE TITLE
Implement timeseries generation 

### ISSUE THREAD

**Issue by leothomas** [NASA-IMPACT/veda-backend#34]
A very important feature for the dashboard is the ability to generate a timeseries analysis for a given AOI + date range. 

The timeseries analysis currently deployed to the NASA Covid Dashboard returns the mean value of the data within the AOI for each requested date. 

This should be updated to include: std. dev, min, max (in addition to mean) - as well as provide the data for download as `.csv`

### Note: 
Due to the fact that the timeseries generation process has to read data from a file and perform calculations on it for _each requested date_ the process's runtime quickly balloons with large AOIs/dateranges.  This has been mitigated by restricting the total area of the AOI (and setting the date range to 3 month by default). One way to mitigate this (and enable AOI analysis for arbitrarily large AOIs/dateranges) would be to "fan-out' the request over multiple lambda instances.

**Comment by moradology** [comment]
Quick question about the runtime issues here: do we have just one file from which data is being read or are there potentially many? If we're dealing with an IO bound performance issue, multiprocessing in a single lambda may just be sufficient (and less of a headache to maintain). If multiple files, the solution may be simple. If one, range reads + some educated guesses might work.

I'm just guessing that things might be IO bound given how trivial the relevant math here is once the numbers are in mem

**Comment by j08lue** [comment]
Wow, thanks for looking through this, @moradology.

We actually have implemented this functionality since this ticket was created: https://staging-raster.delta-backend.com/docs#/Cloud%20Optimized%20GeoTIFF/statistics_cog_statistics_get

https://nasa-impact.github.io/veda-docs/notebooks/quickstarts/timeseries-stac-api.html
