### ISSUE TITLE
Plans for upgrading to TiTiler-PgSTAC 1.0?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-backend#364]
VEDA Backend is currently on TiTiler-PgSTAC v0.8.

https://github.com/NASA-IMPACT/veda-backend/blob/eb6a9229cf52d0a376de82a084cbe980513e3bae/raster_api/runtime/setup.py#L10

Do we have plans for upgrading to 1.0 yet? 

One reason for upgrading is that newer deployments of eoAPI will look for VEDA UI that is compatible with TiTiler-PgSTAC 1.0 and it would be great to move both VEDA UI and VEDA Backend forward together, while we are at it.

Here are the migration guidelines: https://stac-utils.github.io/titiler-pgstac/latest/migrations/v1_migration/#endpoints

## Related

Upgrade from 0.2 to 0.8 about 6 months ago:

- https://github.com/NASA-IMPACT/veda-backend/issues/234

## Acceptance criteria

- [ ] titler-pgstac upgraded to V1.0 in `dev`
- [ ] dashboard testing
- [ ] Add colormaps endpoint for https://github.com/NASA-IMPACT/veda-ui/issues/885

**Comment by anayeaye** [comment]
Putting on the board to plan when we will work this next PI

**Comment by smohiudd** [comment]
FYI titiler-pgstac 1.3.0 depends on titiler.core<0.19 and >=0.18.0. So upgrading titiler core/mosaic/extensions to >=0.18.5,<0.19. 

PR: https://github.com/NASA-IMPACT/veda-backend/pull/398
