### ISSUE TITLE
Remove management of CloudFront distribution from veda-backend

### ISSUE THREAD

**Issue by botanical** [NASA-IMPACT/veda-backend#403]
## Context

- Epic Link: https://github.com/NASA-IMPACT/veda-architecture/issues/469
- ADR: https://github.com/NASA-IMPACT/veda-architecture/pull/464

[veda-routes ](https://github.com/NASA-IMPACT/veda-routes) will be responsible for management CloudFront resources, so we should remove the creation of the distribution from this repo. 

## Acceptance Criteria
- [x] repo is updated to no longer create a CloudFront distribution and related resources

**Comment by botanical** [comment]
@anayeaye @smohiudd , do you think this ticket should also remove the CDK for the custom API domain?

**Comment by anayeaye** [comment]
@botanical you mean like `staging-stac@domain_name.com` and `staging-raster@domain_name.com`?

I think that would make the project easer to understand but I would probably only include that work in the same task if it makes it easier to remove the cloudfront distribution. I think removing that custom subdomain work might be a little messy to extract?

**Comment by botanical** [comment]
> @botanical you mean like `staging-stac@domain_name.com` and `staging-raster@domain_name.com`?
> 
> I think that would make the project easer to understand but I would probably only include that work in the same task if it makes it easier to remove the cloudfront distribution. I think removing that custom subdomain work might be a little messy to extract?

@anayeaye Yep, that's what I meant! Yeah, I will take a look, I think you're right that it might be a bit messy to extract but if not, I'll include that in this issue. Thanks!

**Comment by botanical** [comment]
https://github.com/NASA-IMPACT/veda-backend/pull/422
