### ISSUE TITLE
Upgrade titiler version for exportable renders parameters and formatted viewer links

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#430]
## What
https://github.com/developmentseed/titiler/pull/987

**Comment by vincentsarago** [comment]
I'll backport this feature in a `0.18.8` release (or you'll have to wait for next major version of titiler 😅 )

**Comment by anayeaye** [comment]
@vincentsarago cool - this isn't urgent but it will be exciting to have when it is available!

**Comment by anayeaye** [comment]
This functionality was backported. We do not need to make changes to the backend dependencies
