### ISSUE TITLE
Fix missing path prefix in next page links in GET items response

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#444]
## What
The dynamically produced next page link in an item search response (i.e. `/collections/{collection_id}/items`) is invalid when the API is deployed with a path prefix. The solution is likely upstream so this ticket involves working with stac-fastapi and pgstac.

### Report
> it seems the pagination of the items is not configured correctly, so if you go to, e.g.:
https://openveda.cloud/api/stac/collections/no2-monthly/items
when you look at the "rel":"next"  which indicates the link to fetch the next set of items, it does not have /api/stac/ in the path. "href":"https://openveda.cloud/collections/no2-monthly/items?token=next:no2-monthly:OMI_trno2_0.10x0.10_202212_Col3_V4.nc"  so it seems our client is able to fetch the first 10 items, and then runs into a "forbidden" location

## AC
- [ ] next page link is valid in item search response

**Comment by vincentsarago** [comment]
👍 we should fix this in stac-fastapi-pgstac 🙏

**Comment by smohiudd** [comment]
PR in stac-fastapi-pgstac https://github.com/stac-utils/stac-fastapi-pgstac/pull/164

**Comment by anayeaye** [comment]
@vincentsarago @smohiudd does this mean we need to update our runtime to install `stac-fastapi-pgstac` instead of the  core `stac-fastapi.pgstac` that we currently use? Will we need other modifications?

**Comment by anayeaye** [comment]
We deployed the changes to production and tested
