### ISSUE TITLE
[WIP] Deploy backend to MCP

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-backend#61]
# What
This outline of the work required to deploy the backend stack to MCP is a WIP @abarciauskas-bgse @leothomas @alukach please let me know if this looks right. 

## CDK work
- [x] Bootstrap CDK (also note that a [named toolkit](https://github.com/NASA-IMPACT/delta-backend/blob/develop/cdk.json#L4) was used in UAH when experimenting with V2). **UPDATE** us-east-1 is bootstrapped, but not us-west-2. Testing can begin in us-east-1 now.
- [x] Add MCP T/F configuration variable **UPDATE** [`PERMISSIONS_BOUNDARY_POLICY` used for MCP deployment](https://github.com/NASA-IMPACT/delta-backend/blob/develop/app.py#L24) 
- [x] Add permission boundary if MCP=T (`mcp-tenantOperator` looks right) (stack-level app.py)
- [x] Create RDS in private subnet if MCP=T (change to database/infrastructure/construct.py) [`DELTA_DB_PRIVATE_SUBNETS`](https://github.com/NASA-IMPACT/delta-backend/blob/develop/database/infrastructure/construct.py#L130)causes RDS deployment in private subnets with private accessibility settings.
- [x] ~Request additional `PRIVATE_WITH_NAT` subnets in the MCP VPC (current VPC has only PUBLIC and PRIVATE_ISOLATED but NAT gateways are needed to for the tiler to access COGs stored in external S3 buckets).~ Not needed
- [x] ~Suggested improvement: remove resource naming from RDS construct (this name makes it hard/impossible to replace the resource from a snapshot). This involves removing RDS instance identifier [here](https://github.com/NASA-IMPACT/delta-backend/blob/develop/database/infrastructure/construct.py#L148) and [here](https://github.com/NASA-IMPACT/delta-backend/blob/develop/database/infrastructure/construct.py#L166). This change is incompatible with the current UAH deployments and will cause the database construct to be rebuilt so it may require additional deployment logic or starting a new release branch for MCP.~ Not required
- [x] Suggested improvement: Upgrade pgstac >= v0.5
## Operations work
- [ ] Create EC2 jumpbox and confirm that database admin tasks are possible over SSH
- [x] Coordinate with ingest pipelines to upgrade pypgstac to match the pgstac version (pgstac >0.5 has different loading logic and the upgrade is required) https://github.com/NASA-IMPACT/veda-data-pipelines/issues/162
- [ ] Coordinate with ingest pipeline team to confirm all ingest operations are possible
## Improvements after initial deployment success (or tickets for future work)
- [ ] Obtain a role for github actions and update project to 
- [x] use secret/parameter env variables for deployment
- [ ] Hosted zone for APIs (i.e. veda-backend.com or similar)
- [ ] Deploy stac browser for the MCP delta-backend stack (although this doesn't necessarily need to be MCP hosted) ~No longer needed, can use radiant earth hosted demo. See [README](https://github.com/NASA-IMPACT/delta-backend#stac-browser)~ 

## Resources
[NASA AWS best practices](https://github.com/developmentseed/earthdata-playbook/blob/aws-nasa-best-practices/nasa-aws-best-practices.md)

**Comment by j08lue** [comment]
I assume this is stale but might resurface in the context of the PI Objective to [Develop and blueprint a production data services stack for GHG Center in MCP](https://github.com/NASA-IMPACT/veda-architecture/issues/220)
