### ISSUE TITLE
Enable mosaic based stats  requests

### ISSUE THREAD

**Issue by leothomas** [NASA-IMPACT/veda-backend#70]
[The MosaicTilerFactory](https://github.com/stac-utils/titiler-pgstac/blob/b3b4b40c42b2f4009ab4e078a1ee09d3d61f0f3a/titiler/pgstac/factory.py#L417) enables to request statistics for a `searchId` (instead of a single COG url or STAC Item Id). This makes it possible to generate stats for an AOI in a single step (as opposed to retrieving a list of COGs within the AOI and then requesting the stats for each). 

The danger is that API will need load every file within the AOI into memory in order to generate the stats, which can become very slow/memory intensive with a large number of files. The nature of the VEDA dashboard is such that each stats query is always bounded to a single day, so I assume that there will never be more than a few dozen files being opened. 

In order to enable the endpoint, you just have to add: 
```python
add_statistics=True
```
 to the [MultiBaseTilerFactory](https://github.com/developmentseed/eoAPI/blob/c32a205099e5938dd2070e3496de098abec469b8/src/eoapi/raster/eoapi/raster/app.py#L43-L48) instantiation

Again, a big thank you to @vincentsarago for being one step ahead of everyone else and having already implemented the functionality before we even realized we might need it!

**Comment by ividito** [comment]
Used monitoring tools to assess this endpoint and found some issues with the approach - documented in #125. Closing this issue for now.
